# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - "*"

pr:
  - master
  - releases/*

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: DeleteFiles@1
    displayName: "Delete JUnit files"
    inputs:
      SourceFolder: "$(System.DefaultWorkingDirectory)/junit"
      Contents: "TESTS*.xml"

  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: npm install
    displayName: "npm install"

  - script: npm run build-prod
    displayName: "npm build"

  - script: npm run test-no-watch
    displayName: "npm test"

  - task: PublishTestResults@2
    displayName: "Publish unit test results"
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: "**/TESTS*.xml"
      searchFolder: "$(System.DefaultWorkingDirectory)/junit"
      testRunTitle: "Unit tests"

  - task: PublishCodeCoverageResults@1
    displayName: "Publish code coverage results"
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/*coverage.xml"
      reportDirectory: "$(System.DefaultWorkingDirectory)/coverage"

  - script: npm run lint
    displayName: "npm lint"
    condition: succeededOrFailed()

  - script: ./node_modules/protractor/bin/webdriver-manager update --standalone false --gecko false
    displayName: "update web driver"
    condition: succeededOrFailed()

  # Activate back when issue with webdriver is fixed
  #- script: npm run e2e
  #  displayName: 'npm End to End Test'
  #  condition: succeededOrFailed()

  - task: PublishTestResults@2
    displayName: "Publish End to End test results"
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: JUnit
      testResultsFiles: "**/junit*.xml"
      searchFolder: "$(System.DefaultWorkingDirectory)/e2e/junit"
      testRunTitle: "E2E tests"

  - script: npm run generate-docs-prod
    displayName: "npm Generate Project Documentation"
    condition: succeededOrFailed()

  - task: PublishBuildArtifacts@1
    displayName: "Publish firebase.json"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      PathtoPublish: "$(System.DefaultWorkingDirectory)/firebase.json"
      ArtifactName: "drop"
      publishLocation: "Container"

  - task: PublishBuildArtifacts@1
    displayName: "Publish dist"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      PathtoPublish: "$(System.DefaultWorkingDirectory)/dist"
      ArtifactName: "drop/dist"
      publishLocation: "Container"
